const data = [
  { nodeName: '01 定期报告', children: [{ nodeName: '0101年报' }] },
  {
    nodeName: '02 董事会和监事会',
    children: [{ nodeName: '0201 董事会决议' }, { nodeName: '0204 董事会审议变更证券简称' }],
  },
  {
    nodeName: '03 股东大会',
    children: [
      { nodeName: '0301（召开通知）' },
      { nodeName: '0303（延期）' },
      { nodeName: '0305（取消会议）' },
      { nodeName: '0306（加议案）' },
      { nodeName: '0307（取消议案）' },
      { nodeName: '0308（股东、监事会自行召集召开）' },
      { nodeName: '0311（更正补充）' },
    ],
  },
  {
    nodeName: '04 应当披露的交易',
    children: [
      { nodeName: '0401 购买资产' },
      { nodeName: '0402 出售资产' },
      { nodeName: '0403 对外投资' },
      { nodeName: '0420 矿业权交易' },
      { nodeName: '0425 签订战略框架协议' },
      { nodeName: '0426 与私募基金合作投资' },
    ],
  },
  {
    nodeName: '05 关联交易',
    children: [
      { nodeName: '0502 向关联人提供担保或反担保' },
      { nodeName: '0503 向关联人购买资产' },
      { nodeName: '0504 向关联人出售资产' },
    ],
  },
  {
    nodeName: '06 对外担保',
    children: [{ nodeName: '0606 被担保人可能无法清偿担保债务' }],
  },
  {
    nodeName: '07 募集资金使用与管理',
    children: [{ nodeName: '0704 变更募集资金用途' }],
  },
  {
    nodeName: '08 业绩预告、业绩快报和盈利预测',
    children: [
      { nodeName: '业绩预测公告：0801（预盈）' },
      { nodeName: '0802（盈亏不确定）' },
      { nodeName: '0803（预亏）' },
      { nodeName: '0804（业绩大幅提升）' },
      { nodeName: '0805（业绩大幅下降）' },
      { nodeName: '0809  业绩预告更正' },
      { nodeName: '0811  盈利预测更正' },
    ],
  },
  {
    nodeName: '09 利润分配和资本公积金转增股本',
    children: [
      { nodeName: '0901 实施利润分配和资本公积金转增' },
      { nodeName: '0902 董事会审议高送转' },
      { nodeName: '0903 股东或董事会关于利润分配或转增股本的提议' },
    ],
  },
  {
    nodeName: '11 股份上市流通与股本变动',
    children: [
      { nodeName: '1901（可转债上市）' },
      { nodeName: '1101（首发限售股份上市）' },
      { nodeName: '1102（股改后限售流通股上市）' },
      { nodeName: '1103（非公开发行限售股上市）' },
      { nodeName: '1104（其他类型股份上市）' },
      { nodeName: '1106（配股/增发股份上市）' },
      { nodeName: '1715（换股实施结果、股份变动暨新增股份上市（合并方））' },
    ],
  },
  {
    nodeName: '12 股东增持或减持股份',
    children: [
      { nodeName: '1214  控股股东或实际控制人发生变动的提示' },
      { nodeName: '1216 公开征集股权受让方' },
      { nodeName: '1217 公开征集股权受让方的结果' },
      { nodeName: '1220 股东减持计划' },
      { nodeName: '1221 股东减持进展' },
      { nodeName: '1222 股东增持计划' },
      { nodeName: '1223 股东增持进展' },
    ],
  },
  {
    nodeName: '13 权益变动报告书和（要约）收购',
    children: [
      { nodeName: '1301 减持简式权益变动报告书' },
      { nodeName: '1302 增持简式权益变动报告书' },
      { nodeName: '1303 增持详式权益变动报告书' },
      { nodeName: '1304 收购报告书摘要' },
      { nodeName: '1306 要约收购报告书摘要' },
      { nodeName: '1312 要约收购结果' },
    ],
  },
  {
    nodeName: '14 股权型再融资',
    children: [
      { nodeName: '1401（与再融资有关的停牌）' },
      { nodeName: '1601（进入重大资产重组程序停牌）' },
      { nodeName: '1602（重大资产重组停牌期延长）' },
      { nodeName: '1701（进入吸收合并程序停牌）' },
      { nodeName: '1702（吸收合并停牌期延长）' },
      { nodeName: '2902（因存在暂停上市风险而连续停牌）' },
      { nodeName: '1603（取消重大资产重组并复牌）' },
      { nodeName: '1703（取消吸收合并复牌）' },
      { nodeName: '3301（停复牌提示性公告）' },
      { nodeName: '1402 再融资预案' },
      { nodeName: '1403 取消再融资' },
      { nodeName: '1407 发审委审核结果' },
      { nodeName: '1411 配股发行' },
      { nodeName: '1510 发行公司债获批' },
      { nodeName: '3505 优先股公开发行' },
    ],
  },
  {
    nodeName: '15 其他再融资',
    children: [{ nodeName: '1411 配股发行' }, { nodeName: '1510发行公司债获批' }, { nodeName: '3505 优先股公开发行' }],
  },
  {
    nodeName: '16 重大资产重组',
    children: [
      { nodeName: '1401（与再融资有关的停牌）' },
      { nodeName: '1601（进入重大资产重组程序停牌）' },
      { nodeName: '1602（重大资产重组停牌期延长）' },
      { nodeName: '1701（进入吸收合并程序停牌）' },
      { nodeName: '1702（吸收合并停牌期延长）' },
      { nodeName: '2902（因存在暂停上市风险而连续停牌）' },
      { nodeName: '1603（取消重大资产重组并复牌）' },
      { nodeName: '1703（取消吸收合并复牌）' },
      { nodeName: '3301（停复牌提示性公告）' },
      { nodeName: '1604 许可类重大资产重组预案摘要' },
      { nodeName: '1608 重组委审核结果' },
      { nodeName: '1610 重大资产重组未予核准' },
      { nodeName: '1613 重大资产重组终止' },
      { nodeName: '1614 非许可类重大资产重组预案摘要' },
    ],
  },
  {
    nodeName: '17 吸收合并',
    children: [
      { nodeName: '1401（与再融资有关的停牌）' },
      { nodeName: '1601（进入重大资产重组程序停牌）' },
      { nodeName: '1602（重大资产重组停牌期延长）' },
      { nodeName: '1701（进入吸收合并程序停牌）' },
      { nodeName: '1702（吸收合并停牌期延长）' },
      { nodeName: '2902（因存在暂停上市风险而连续停牌）' },
      { nodeName: '1603（取消重大资产重组并复牌）' },
      { nodeName: '1703（取消吸收合并复牌）' },
      { nodeName: '3301（停复牌提示性公告）' },
      { nodeName: '1704 吸收合并预案' },
      { nodeName: '1710 吸收合并未予核准' },
      { nodeName: '1901（可转债上市）' },
      { nodeName: '1101（首发限售股份上市）' },
      { nodeName: '1102（股改后限售流通股上市）' },
      { nodeName: '1102（股改后限售流通股上市）' },
      { nodeName: '1104（其他类型股份上市）' },
      { nodeName: '1106（配股/增发股份上市）' },
      { nodeName: '1715（换股实施结果、股份变动暨新增股份上市（合并方））' },
      { nodeName: '1718 吸收合并终止' },
    ],
  },
  {
    nodeName: '18 回购股份',
    children: [{ nodeName: '1801 回购方案' }],
  },
  {
    nodeName: '19 可转换公司债 ',
    children: [
      { nodeName: '1901（可转债上市）' },
      { nodeName: '1101（首发限售股份上市）' },
      { nodeName: '1102（股改后限售流通股上市）' },
      { nodeName: '1103（非公开发行限售股上市）' },
      { nodeName: '1104（其他类型股份上市）' },
      { nodeName: '1106（配股/增发股份上市）' },
      { nodeName: '1715（换股实施结果、股份变动暨新增股份上市（合并方））' },
      { nodeName: '1906（可转债付息）' },
      { nodeName: '1909（可转债赎回结果及兑付摘牌）' },
      { nodeName: '1916（可转债到期兑付及摘牌）' },
      { nodeName: '2001（公司债付息）' },
      { nodeName: '2002（公司债兑付及摘牌）' },
      { nodeName: '2017（公司债券赎回结果及摘牌）' },
      { nodeName: '2007（公司债提前偿还）' },
      { nodeName: '1921 可转债募集说明书摘要' },
      { nodeName: '1922 可转债发行' },
    ],
  },
  {
    nodeName: '20 公司债',
    children: [
      { nodeName: ' 1906（可转债付息）' },
      { nodeName: '1909（可转债赎回结果及兑付摘牌）' },
      { nodeName: '1916（可转债到期兑付及摘牌）' },
      { nodeName: '2001（公司债付息）' },
      { nodeName: '2002（公司债兑付及摘牌）' },
      { nodeName: '2017（公司债券赎回结果及摘牌）' },
      { nodeName: '2007（公司债提前偿还）' },
      { nodeName: '2906（终止上市公告）' },
      { nodeName: '2018（公司债券暂停上市）' },
      { nodeName: '2019（公司债券恢复上市）' },
      { nodeName: '2903（暂停上市公告）' },
    ],
  },
  {
    nodeName: '21 股权激励及员工持股计划',
    children: [
      { nodeName: '2101 股权激励计划草案摘要' },
      { nodeName: '2105 股权激励计划终止' },
      { nodeName: '2130 员工持股计划草案' },
      { nodeName: '2132 员工持股计划变更' },
    ],
  },
  {
    nodeName: '23 诉讼和仲裁',
    children: [
      { nodeName: '2301 诉讼' },
      { nodeName: '2303 诉讼结果' },
      { nodeName: '2304 仲裁' },
      { nodeName: '2306 仲裁结果' },
    ],
  },
  {
    nodeName: '24 股东股份被质押冻结或司法拍卖',
    children: [
      { nodeName: '2401 股份被质押' },
      { nodeName: '2402 股份被冻结' },
      { nodeName: '2405 股份被司法拍卖' },
      { nodeName: '2408 5%以上股份权利受限或解除' },
    ],
  },
  {
    nodeName: '25 破产与重整',
    children: [
      { nodeName: '2501 申请重整、和解或破产清算' },
      { nodeName: '2509 法院裁定重整、和解或破产清算' },
      { nodeName: '2511  法院裁定重整、和解或破产清算计划实施完成' },
    ],
  },
  {
    nodeName: '26 其他重大事项',
    children: [
      { nodeName: '2601 重大亏损或重大损失' },
      { nodeName: '2602 发生重大债务或重大债权到期未获清偿' },
      { nodeName: '2603 或有重大违约责任或大额赔偿责任' },
      { nodeName: '2604 计提大额资产减值准备' },
      { nodeName: '2608 资产被查封、扣押、冻结或拍卖' },
      { nodeName: '2609 主要业务陷入停顿' },
      { nodeName: '2610 公司涉嫌违法违规被其他机构调查' },
      { nodeName: '2611 重大行政、刑事处罚' },
      { nodeName: '2612 公司法定代表人或者总经理无法履行职责' },
      { nodeName: '2613 董监高被调查、处罚或被采取强制措施' },
      { nodeName: '2614 公司被证监会立案调查' },
      { nodeName: '2615 重要前期会计差错更正' },
      { nodeName: '2616 生产经营、外部条件发生重大变化' },
    ],
  },
  {
    nodeName: '27 公司重要基本信息变化',
    children: [
      { nodeName: '2701 变更公司名称' },
      { nodeName: '2702 变更证券简称' },
      { nodeName: '2707 公司章程发生修订' },
      { nodeName: '2708 变更会计师事务所' },
      { nodeName: '2710 变更会计政策或者会计估计' },
      { nodeName: '2711 变更保荐机构' },
      { nodeName: '2713（公司董事长/法定代表人辞职）' },
      { nodeName: '2714（公司董事、监事、高级管理人员辞职）' },
      { nodeName: '2715（董事会秘书辞职）' },
    ],
  },
  {
    nodeName: '28 风险警示',
    children: [
      { nodeName: '2801（实施其他风险警示）' },
      { nodeName: '2802（实施退市风险警示）' },
      { nodeName: '2805（撤销其他风险警示）' },
      { nodeName: '2806（撤销退市风险警示）' },
    ],
  },
  {
    nodeName: '29 暂停、恢复和终止上市',
    children: [
      { nodeName: '2901 暂停上市风险提示' },
      { nodeName: '1401（与再融资有关的停牌）' },
      { nodeName: '1601（进入重大资产重组程序停牌）' },
      { nodeName: '1602（重大资产重组停牌期延长）' },
      { nodeName: '1701（进入吸收合并程序停牌）' },
      { nodeName: '1702（吸收合并停牌期延长）' },
      { nodeName: '2902（因存在暂停上市风险而连续停牌）' },
      { nodeName: '1603（取消重大资产重组并复牌）' },
      { nodeName: '1703（取消吸收合并复牌）' },
      { nodeName: '3301（停复牌提示性公告）' },
      { nodeName: '2906（终止上市公告）' },
      { nodeName: '2018（公司债券暂停上市）' },
      { nodeName: '2019（公司债券恢复上市）' },
      { nodeName: '2903（暂停上市公告）' },
    ],
  },
  {
    nodeName: '31 规范运作',
    children: [{ nodeName: '3101  征集委托投票权' }],
  },
  {
    nodeName: '33 停复牌提示性公告',
    children: [
      { nodeName: '1401（与再融资有关的停牌）' },
      { nodeName: '1601（进入重大资产重组程序停牌）' },
      { nodeName: '1602（重大资产重组停牌期延长）' },
      { nodeName: '1701（进入吸收合并程序停牌）' },
      { nodeName: '1702（吸收合并停牌期延长）' },
      { nodeName: '2902（因存在暂停上市风险而连续停牌）' },
      { nodeName: '1603（取消重大资产重组并复牌）' },
      { nodeName: '1703（取消吸收合并复牌）' },
      { nodeName: '3301（停复牌提示性公告）' },
    ],
  },
  {
    nodeName: '35 优先股',
    children: [
      { nodeName: '3501 优先股发行预案' },
      { nodeName: '1411 配股发行' },
      { nodeName: '1510发行公司债获批 ' },
      { nodeName: '3505 优先股公开发行' },
      { nodeName: '0901（实施利润分配和资本公积金转增）' },
      { nodeName: '3509（优先股股息分派）' },
    ],
  },
];

module.exports = data;
